sudo: required
services:
   - docker
   
before_install: 
   - docker build -t littlepenguin/docker-react-travis  -f Dockerfile2.dev .

script:
   - docker run -e CI=true littlepenguin/docker-react-travis  npm run test 

deploy:
   provider: elasticbeanstalk
   region: "us-east-2"
   app: "UdemyTravisTest"
   env: "UdemyTravisTest-env"
   bucket_name: "elasticbeanstalk-us-east-2-743978757333"
   bucket_path: "UdemyTravisTest"
   on:
      branch: main
   access_key_id: "$AWS_ACCESS_KEY"
   secret_access_key: "$AWS_SECRET_KEY"



#udemysection7-env.eba-fvssyvpn.us-east-2.elasticbeanstalk.com
