sudo: required
services:
   - docker
   
before_install: 
   - docker build -t littlepenguin/docker-react-travis  -f Dockerfile2.dev .

script:
   - docker run -e CI=true littlepenguin/docker-react-travis  npm run test 
